export const htmlContent = `
   <!DOCTYPE html>
<html lang="vi-VN">
  <head>
    <link
      rel="stylesheet"
      href="https://static.tacdn.com/assets/aej5c8pzmc08-c.css"
      crossorigin=""
    />
    <link
      rel="stylesheet"
      href="https://static.tacdn.com/assets/cjerkd.Pq2ARUF.css"
      crossorigin=""
    />
    <script
      src="https://static.tacdn.com/assets/p2apm9r9x0qg-c.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
    <script
      src="https://static.tacdn.com/assets/9wrliy5ctarr-c.vi-VN.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
    <script
      src="https://static.tacdn.com/assets/im/98810f7b.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
    <script
      src="https://static.tacdn.com/assets/gg6fk5.j2mMgQs.vi-VN.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
    <script
      src="https://static.tacdn.com/assets/mqwhqn.8lVwIqc.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
    <script
      src="https://static.tacdn.com/assets/8cre3h.59xo0IH.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
    <script
      src="https://static.tacdn.com/assets/nflkuf.plgMk-H.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
    <script
      src="https://static.tacdn.com/assets/w7gsd9.ArOgZVx.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
    <script
      src="https://static.tacdn.com/assets/cjerkd.Pq2ARUF.vi-VN.js"
      async=""
      crossorigin=""
      fetchpriority="low"
    ></script>
  </head>
</html>
  `;
